toolset = {"02": "Red,Lite Blue,0",
           "06": "Lite Blue,Yellow,0",
           "10": "Yellow,Lavender,0",
           "14": "Lavender,Green,0",
           "18": "Green,Orange,0",
           "22": "Orange,Dark Blue,0",
           "27": "Dark Blue,Lite Blue,1",
           "31": "Lite Blue,Green,0",
           "35": "Green,Brown,-1",
           "39": "Brown,Yellow,2",
           "43": "Yellow,Orange,0",
           "47": "Orange,Red,1",
           "52": "Red,Orange,0",
           "56": "Orange,Yellow,1",
           "60": "Yellow,Brown,-1",
           "64": "Brown,Green,2",
           "68": "Green,Lite Blue,1",
           "72": "Lite Blue,Dark Blue,0",
           "77": "Dark Blue,Orange,1",
           "81": "Orange,Green,1",
           "85": "Green,Lavender,1",
           "89": "Lavender,Yellow,1",
           "93": "Yellow,Lite Blue,1",
           "97": "Lite Blue,Red,1"}
