toolset = {"02": "Red, Lite Blue",
           "06": "Lite Blue, Yellow",
           "10": "Yellow, Lavender",
           "14": "Lavender, Green",
           "18": "Green, Orange",
           "22": "Orange, Dark Blue",
           "27": "Dark Blue, Lite Blue",
           "31": "Lite Blue, Green",
           "35": "Green, Brown",
           "39": "Brown, Yellow",
           "43": "Yellow, Orange",
           "47": "Orange, Red",
           "52": "Red, Orange",
           "56": "Orange, Yellow",
           "60": "Yellow, Brown",
           "64": "Brown, Green",
           "68": "Green, Lite Blue",
           "72": "Lite Blue, Dark Blue",
           "77": "Dark Blue, Orange",
           "81": "Orange, Green",
           "85": "Green, Lavender",
           "89": "Lavender, Yellow",
           "93": "Yellow, Lite Blue",
           "97": "Lite Blue, Red"}
